id: P5CA147A3
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS22935
  title: ས་སྐྱ་པའི་ལམ་འབྲས་ཀྱི་ཆོས་སྐོར་གཅེས་བཏུས།
  volumes:
    0eca3ac158e84ed08f781e670096c06e:
      image_group_id: I8LS22937
      title: ''
      base_file: v001.txt
  author: ''
