id: I6D882DC6
legacy_id: P5CA147A3
ocr_import_info:
  bdrc_scan_id: W8LS22935
  source: bdrc
  ocr_info:
    timestamp: '2022-03-28T10:25:58'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T05:02:49.726834+00:00'
last_modified: 2022-09-04 13:03:15.472199
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS22935
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS22935
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ས་སྐྱ་པའི་ལམ་འབྲས་ཀྱི་ཆོས་སྐོར་གཅེས་བཏུས།
  author: ཏཱ་ལའི་བླ་མ ༠༥་ངག་དབང་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9814778147198014
  ocr_word_median_confidence_index: 0.99
quality: null
bases:
  I8LS22937:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS22937
      total_pages: 504
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS22937.txt
    statistics:
      ocr_word_median_confidence_index: 0.99
      ocr_word_mean_confidence_index: 0.9814778147198014
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
